pps-1

diff --git a/.github/workflows/build-and-push-ecr.yml b/.github/workflows/build-and-push-ecr.yml
--- a/.github/workflows/build-and-push-ecr.yml
+++ b/.github/workflows/build-and-push-ecr.yml
@@ -6,16 +6,28 @@ on:
       - qa
       - pps-master
 
-
+  workflow_dispatch:
+    inputs:
+      branch:
+        description: "Branch to deploy"
+        required: true
+        default: qa
+        type: choice
+        options:
+          - qa
+          - pps-master
 
 env:
   ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
   IMAGE_NAME: ${{ vars.IMAGE_NAME }}
+  REGION: ${{ secrets.REGION }}
 
 jobs:
   build-and-push-ecr:
-    runs-on: ${{ github.ref_name == 'pps-master' && fromJson('["self-hosted","production"]') || fromJson('["self-hosted","dev"]') }}
-    
+    runs-on: ${{ (github.event.inputs.branch || github.ref_name) == 'pps-master' && fromJson('["self-hosted","production"]') || fromJson('["self-hosted","dev"]') }}
+
+    environment: ${{ (github.event.inputs.branch || github.ref_name) == 'pps-master' && 'prod' || 'dev' }}
+
     permissions:
       id-token: write
       contents: read
@@ -23,17 +35,20 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
-
+        with:
+                  ref: ${{ github.event.inputs.branch || github.ref_name }}
       - name: Set Environment Variables
         run: |
-          BRANCH_NAME="${GITHUB_REF##*/}"
+          BRANCH_NAME="${{ github.event.inputs.branch || github.ref_name }}"
           echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
-          echo "IMAGE_TAG=build-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
-      
+          echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
+
           if [[ "$BRANCH_NAME" == "pps-master" ]]; then
             echo "ENV=production" >> $GITHUB_ENV
+            echo "${{ vars.ENV_FILE_PROD }}" > .env
           elif [[ "$BRANCH_NAME" == "qa" ]]; then
             echo "ENV=dev" >> $GITHUB_ENV
+            echo "${{ vars.ENV_FILE_DEV }}" > .env
           else
             echo "Unsupported branch: $BRANCH_NAME"
             exit 1
@@ -41,8 +56,8 @@ jobs:
 
       - name: Login to Amazon ECR
         run: |
-          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
-        
+          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
+
 
       - name: Build Docker Image
         run: |
@@ -53,8 +68,13 @@ jobs:
         run: |
           docker push $ECR_REGISTRY/$IMAGE_NAME-$ENV:$IMAGE_TAG
 
+      - name: Remove Built Docker Image
+        if: always()
+        run: |
+          docker rmi $ECR_REGISTRY/$IMAGE_NAME-$ENV:$IMAGE_TAG || true
+
       # - name: Cleanup Docker
-      #   if: always()
+      #   if: always() && vars.CLEANUP_DOCKER == 'true'
       #   run: |
       #     docker system prune -af --volumes
           
@@ -63,11 +83,11 @@ jobs:
         run: |
           find "$GITHUB_WORKSPACE" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
 
-# Calling the deploy workflow directly
+
   trigger-deploy:
     needs: build-and-push-ecr
     uses: ./.github/workflows/deploy.yml
     with:
-      branch: ${{ github.ref_name }}
-      image_tag: build-${{ github.run_number }}
-    secrets: inherit # This passes all your secrets (ECR, SSH, etc.) to the next file
+      branch: ${{ github.event.inputs.branch || github.ref_name }}
+      image_tag: ${{ github.run_number }}
+    secrets: inherit 
